##
##
##_______COMMANDS_____
## docker-compose pull
## docker compose -f "docker-compose.yml" up -d --build --remove-orphans
## docker system prune 
version: "3.9"
services:
##
##
##_______SYSTEM_____
##____________________ Portainer [SYSTEM/Docker]
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/portainer/data:/data
    ports:
      - 9000:9000
    labels:
      plugsy.name: Portainer
      plugsy.link: http://$IPADDRESS:9000
      plugsy.category: System
##
##____________________ Plugsy [SYSTEM/Homepage]
  plugsy:
    container_name: plugsy
    image: plugsy/core:latest
    restart: always
    networks: 
      - web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:3000
##
##
##______PRIVACY_______
##______________________ AdGuard Home [PRIVACY/Blocker]
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: always
    network_mode: host
    volumes:
       - $DOCKERDIR/adguardhome/conf:/opt/adguardhome/conf
    labels:
      plugsy.name: AdGuard
      plugsy.link: http://$IPADDRESS:3000
      plugsy.category: Network
##
##
##________MEDIA________
##_____________________ Jellyfin [MEDIA/Library] 
  jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin:latest
    restart: always
    networks: 
      - web-proxy
    # Required for Intel QuickSync/VAAPI hardware accelerated video encoding/transcoding
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002 #optional
    volumes:
      - $DOCKERDIR/jellyfin/config:/config
      - $MEDIALIBRARY/tvseries:/tv
      - $MEDIALIBRARY/movies:/movies
    ports:
      - 8096:8096
    labels:
      plugsy.name: Jellyfin
      plugsy.link: http://$IPADDRESS:8096
      plugsy.category: Media 
      org.hotio.pullio.update: true
##
##____________________ Transmission [MEDIA/download-client]
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    restart: always
    networks:
      - web-proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - $DOCKERDIR/Transmission/data:/config
      - $MEDIALIBRARY/downloads/bitorrent:/downloads
      - $MEDIALIBRARY/downloads/bitorrent/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels: 
      org.hotio.pullio.update: true
      plugsy.name: Transmission
      plugsy.link: http://$IPADDRESS:9091
      plugsy.category: Media
##
##____________________ Prowlarr [MEDIA/torrent-proxy for Sonarr&Radarr]
  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:latest
    networks: 
      - web-proxy
    restart: always
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: 002
      TZ: $TZ
    volumes:
      - $DOCKERDIR/prowlarr/config:/config
    ports:
      - 9696:9696
    labels:
      plugsy.name: Prowlarr (Indexer)
      plugsy.link: http://$IPADDRESS:9696
      plugsy.category: Media
      org.hotio.pullio.update: true
##
##____________________ Sonarr [MEDIA/PVR-TVshows]
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    networks: 
      - web-proxy
    restart: always
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/sonarr/config:/config
      - $MEDIALIBRARY/tvseries:/tv
      - $MEDIALIBRARY/downloads/bitorrent:/downloads
    ports:
      - 8989:8989
    labels:
      plugsy.name: Sonarr (series)
      plugsy.link: http://$IPADDRESS:8989
      plugsy.category: Media
      org.hotio.pullio.update: true
##
##____________________ Radarr [MEDIA/PVR-Movies]
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    networks: 
      - web-proxy
    restart: always
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/radarr/config:/config
      - $MEDIALIBRARY/movies:/movies
      - $MEDIALIBRARY/downloads/bitorrent:/downloads
    ports:
      - 7878:7878
    labels:
      plugsy.name: Radarr (movies)
      plugsy.link: http://$IPADDRESS:7878
      plugsy.category: Media 
      org.hotio.pullio.update: true
##
##____________________ Bazarr [MEDIA/subtitles]
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    networks: 
      - web-proxy
    restart: always
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/bazarr/config:/config
      - $MEDIALIBRARY/movies:/movies
      - $MEDIALIBRARY/tvseries:/tv
    ports:
      - 6767:6767
    labels:
      plugsy.name: Bazarr (subtitles)
      plugsy.link: http://$IPADDRESS:6767
      plugsy.category: Media
      org.hotio.pullio.update: true
##
##____________________ Lidarr [MEDIA/PVR-Music]
  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr:latest
    networks: 
      - web-proxy
    restart: always
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/lidarr/config:/config
      - $DATAPOOL/media:/Media
    ports:
      - 8686:8686
    labels:
      plugsy.name: Lidarr (music)
      plugsy.link: http://$IPADDRESS:8686
      plugsy.category: Media
      org.hotio.pullio.update: true
##
##____________________ Plex
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - VERSION=docker
      - PLEX_CLAIM=$PLEXCLAIM
    volumes:
      - $DOCKERDIR/plex/library:/config
      - $MEDIALIBRARY/tvseries:/tv
      - $MEDIALIBRARY/movies:/movies
    labels:
      plugsy.name: Plex
      plugsy.link: http://$IPADDRESS:32400
      plugsy.category: Media
##
##____________________ Readarr
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    networks: 
      - web-proxy
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/readarr/data:/config
      - $MEDIALIBRARY/Books:/books #optional
      - $MEDIALIBRARY/downloads/bitorrent:/downloads #optional
    ports:
      - 8787:8787
    labels:
      plugsy.name: Readarr (Books)
      plugsy.link: http://$IPADDRESS:8787
      plugsy.category: Media
      org.hotio.pullio.update: true
##
##____________________ Ombi
  ombi:
    container_name: ombi
    image: lscr.io/linuxserver/ombi:latest
    networks: 
      - web-proxy
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - BASE_URL=/ombi #optional
    volumes:
      - $DOCKERDIR/ombi/config:/config
    ports:
      - 3579:3579
    labels:
      plugsy.name: Ombi (Plex Request)
      plugsy.link: http://$IPADDRESS:3579
      plugsy.category: Media
      org.hotio.pullio.update: true
##
##
##________MONITORING________
##_____________________ Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - web-proxy
    restart: always
    volumes:
      - $DOCKERDIR/prometheus/config:/etc/prometheus
      - $DOCKERDIR/prometheus/data:/prometheus
    ports:
      - "9090:9090"
    labels:
      plugsy.name: Prometheus
      plugsy.link: http://$IPADDRESS:9090
      plugsy.category: Monitoring
##
##_____________________ Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - web-proxy
    restart: always
    volumes:
      - $DOCKERDIR/grafana/data:/var/lib/grafana
      - $DOCKERDIR/grafana/config:/etc/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    labels:
      plugsy.name: Grafana
      plugsy.link: http://$IPADDRESS:3001
      plugsy.category: Monitoring
##
##
##________TOOLS________
##_____________________ VS Code
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    networks:
      - web-proxy
    restart: always
    volumes:
      - $DOCKERDIR/code-server/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    ports:
      - 8443:8443
    labels:
      plugsy.name: VS Code
      plugsy.link: http://$IPADDRESS:8443
      plugsy.category: Tools
##
##_____________________ Duplicati
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    networks:
      - web-proxy
    restart: always
    volumes:
      - $DOCKERDIR/duplicati/config:/config
      - $MEDIALIBRARY/backups:/backups
      - /home/esteban/docker:/source
    ports:
      - 8200:8200
    labels:
      plugsy.name: Duplicati
      plugsy.link: http://$IPADDRESS:8200
      plugsy.category: Tools
##
##_____________________ Baby Buddy
  babybuddy:
    container_name: babybuddy
    image: lscr.io/linuxserver/babybuddy:latest
    networks:
      - web-proxy
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/babybuddy/config:/config
    ports:
      - 8030:8000
    labels:
      plugsy.name: Babybuddy
      plugsy.link: http://$IPADDRESS:8030
      plugsy.category: Tools
##
##_____________________ Ubooquity
  ubooquity:
    container_name: ubooquity
    image: lscr.io/linuxserver/ubooquity:latest
    networks:
      - web-proxy
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MAXMEM=
    volumes:
      - $DOCKERDIR/ubooquity/config:/config
      - $MEDIALIBRARY/Books:/books
      - $MEDIALIBRARY/Comics:/comics
    ports:
      - 2202:2202
      - 2203:2203
    labels:
      plugsy.name: Ubooquity
      plugsy.link: http://$IPADDRESS:2202/ubooquity
      plugsy.category: Tools
##
##_____________________ EmulatorJS
  emulatorjs:
    container_name: emulatorjs
    image: lscr.io/linuxserver/emulatorjs:latest
    networks:
      - web-proxy
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/emulatorjs/config:/config
      - $DOCKERDIR/emulatorjs/data:/data
    ports:
      - 3004:3000
      - 84:80
      - 4001:4001 #optional
    labels:
      plugsy.name: EmulatorJS
      plugsy.link: http://$IPADDRESS:84
      plugsy.category: Games
##
##
##________DEVOPS________
##
##_____________________ Jenkins
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    networks:
      - web-proxy
    restart: always
    volumes:
      - $DOCKERDIR/jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - 8080:8080
      - 50000:50000
    labels:
      plugsy.name: Jenkins
      plugsy.link: http://$IPADDRESS:8080
      plugsy.category: DevOps
##
##_____________________ GitLab
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    networks:
      - web-proxy
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - 8929:8929
      - 2224:22
    volumes:
      - $DOCKERDIR/gitlab/config:/etc/gitlab
      - $DOCKERDIR/gitlab/logs:/var/log/gitlab
      - $DOCKERDIR/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      plugsy.name: GitLab
      plugsy.link: http://$IPADDRESS:8929
      plugsy.category: DevOps
##
##
##_________NETWORKS_______
networks:
  web-proxy:
    external: true